version: 2

jobs:

  build-website:
    docker:
      - image: ckhrulev/pism-website:0.1.0

    steps:
      - checkout
      - run:
          name: Build the website 
          command: make DESTDIR=/tmp/pism/website
      - persist_to_workspace:
          root: /tmp/pism/
          paths: website

  deploy-website:
    docker:
      - image: node:8.10.0

    steps:
      - checkout
      - attach_workspace:
          at: website
      - run:
          name: Install and configure dependencies
          command: |
            npm install -g --silent gh-pages@2.0.1
            git config user.email "ckhroulev@alaska.edu"
            git config user.name "CI Builder (PISM website)"
      - add_ssh_keys:
          fingerprints:
            - "15:22:79:ff:0a:1d:aa:5a:8e:bb:e1:94:51:2e:67:2f"
      - run:
          name: Deploy the website to GitHub Pages
          command: >-
            gh-pages --dotfiles
            --message "[skip ci] Update the website"
            --dist website

workflows:
  version: 2
  build-and-test:
    jobs:
      - build-website
      # - deploy-website:
      #     requires:
      #       - build-website
      #     filters:
      #       branches:
      #         only: main
